"""AUTO-GENERATED by scripts/generate_sync.py - DO NOT EDIT.

Source: repository_builder.py

This module provides synchronous versions of the async classes.
Changes should be made to the source file, then regenerated.
"""

import warnings
from typing import TYPE_CHECKING, Any

from .exceptions import NamespaceNotFoundError
from .limiter import OnUnavailable as OnUnavailable
from .naming import normalize_stack_name

if TYPE_CHECKING:
    from .models import OnUnavailableAction, StackOptions
    from .sync_repository import SyncRepository


class SyncRepositoryBuilder:
    """Fluent builder for constructing a fully initialized SyncRepository.

    All configuration methods return ``self`` for chaining. Call ``build()``
    to perform initialization and get a ``SyncRepository``.
    """

    def __init__(
        self, name: str, region: str | None = None, *, endpoint_url: str | None = None
    ) -> None:
        self._name = normalize_stack_name(name)
        self._region = region
        self._endpoint_url = endpoint_url
        self._namespace_name = "default"
        self._config_cache_ttl = 60
        self._auto_update = True
        self._bucket_ttl_multiplier = 7
        self._on_unavailable: OnUnavailableAction | None = None
        self._infra_options: dict[str, Any] = {}
        self._parallel_mode: str = "auto"

    def namespace(self, name: str) -> "SyncRepositoryBuilder":
        """Set the namespace to resolve during build (default: "default")."""
        self._namespace_name = name
        return self

    def config_cache_ttl(self, seconds: int) -> "SyncRepositoryBuilder":
        """Set config cache TTL in seconds (default: 60, 0 to disable)."""
        self._config_cache_ttl = seconds
        return self

    def auto_update(self, enabled: bool) -> "SyncRepositoryBuilder":
        """Enable/disable auto-update of Lambda on version mismatch (default: True)."""
        self._auto_update = enabled
        return self

    def bucket_ttl_multiplier(self, value: int) -> "SyncRepositoryBuilder":
        """Set bucket TTL multiplier (default: 7, 0 to disable)."""
        self._bucket_ttl_multiplier = value
        return self

    def on_unavailable(self, value: "OnUnavailableAction") -> "SyncRepositoryBuilder":
        """Set on_unavailable behavior for the namespace ("allow" or "block").

        This is persisted as the system-level default via set_system_defaults().
        """
        self._on_unavailable = value
        return self

    def snapshot_windows(self, value: str) -> "SyncRepositoryBuilder":
        """Set snapshot windows (e.g., "hourly,daily")."""
        self._infra_options["snapshot_windows"] = value
        return self

    def usage_retention_days(self, value: int) -> "SyncRepositoryBuilder":
        """Set usage snapshot retention in days."""
        self._infra_options["usage_retention_days"] = value
        return self

    def audit_retention_days(self, value: int) -> "SyncRepositoryBuilder":
        """Set audit record retention in days."""
        self._infra_options["audit_retention_days"] = value
        return self

    def enable_aggregator(self, value: bool = True) -> "SyncRepositoryBuilder":
        """Enable/disable Lambda aggregator."""
        self._infra_options["enable_aggregator"] = value
        return self

    def pitr_recovery_days(self, value: int | None) -> "SyncRepositoryBuilder":
        """Set Point-in-Time Recovery period (1-35, None for AWS default)."""
        self._infra_options["pitr_recovery_days"] = value
        return self

    def log_retention_days(self, value: int) -> "SyncRepositoryBuilder":
        """Set CloudWatch log retention in days."""
        self._infra_options["log_retention_days"] = value
        return self

    def lambda_timeout(self, value: int) -> "SyncRepositoryBuilder":
        """Set Lambda timeout in seconds (1-900)."""
        self._infra_options["lambda_timeout"] = value
        return self

    def lambda_memory(self, value: int) -> "SyncRepositoryBuilder":
        """Set Lambda memory in MB (128-3008)."""
        self._infra_options["lambda_memory"] = value
        return self

    def enable_alarms(self, value: bool = True) -> "SyncRepositoryBuilder":
        """Enable/disable CloudWatch alarms."""
        self._infra_options["enable_alarms"] = value
        return self

    def alarm_sns_topic(self, value: str | None) -> "SyncRepositoryBuilder":
        """Set SNS topic ARN for alarm notifications."""
        self._infra_options["alarm_sns_topic"] = value
        return self

    def lambda_duration_threshold_pct(self, value: int) -> "SyncRepositoryBuilder":
        """Set duration alarm threshold as percentage of timeout (1-100)."""
        self._infra_options["lambda_duration_threshold_pct"] = value
        return self

    def permission_boundary(self, value: str | None) -> "SyncRepositoryBuilder":
        """Set IAM permission boundary (policy name or full ARN)."""
        self._infra_options["permission_boundary"] = value
        return self

    def role_name_format(self, value: str | None) -> "SyncRepositoryBuilder":
        """Set format template for IAM role names."""
        self._infra_options["role_name_format"] = value
        return self

    def policy_name_format(self, value: str | None) -> "SyncRepositoryBuilder":
        """Set format template for managed policy names."""
        self._infra_options["policy_name_format"] = value
        return self

    def enable_audit_archival(self, value: bool = True) -> "SyncRepositoryBuilder":
        """Enable/disable S3 audit archival."""
        self._infra_options["enable_audit_archival"] = value
        return self

    def audit_archive_glacier_days(self, value: int) -> "SyncRepositoryBuilder":
        """Set days before transitioning archives to Glacier IR."""
        self._infra_options["audit_archive_glacier_days"] = value
        return self

    def enable_tracing(self, value: bool = True) -> "SyncRepositoryBuilder":
        """Enable/disable X-Ray tracing."""
        self._infra_options["enable_tracing"] = value
        return self

    def create_iam_roles(self, value: bool = True) -> "SyncRepositoryBuilder":
        """Create App/Admin/ReadOnly IAM roles (default: False)."""
        self._infra_options["create_iam_roles"] = value
        return self

    def create_iam(self, value: bool = True) -> "SyncRepositoryBuilder":
        """Create IAM resources (policies and roles)."""
        self._infra_options["create_iam"] = value
        return self

    def aggregator_role_arn(self, value: str | None) -> "SyncRepositoryBuilder":
        """Set existing IAM role ARN for the Lambda aggregator."""
        self._infra_options["aggregator_role_arn"] = value
        return self

    def enable_deletion_protection(self, value: bool = True) -> "SyncRepositoryBuilder":
        """Enable DynamoDB table deletion protection."""
        self._infra_options["enable_deletion_protection"] = value
        return self

    def tags(self, value: dict[str, str] | None) -> "SyncRepositoryBuilder":
        """Set user-defined tags for the CloudFormation stack."""
        self._infra_options["tags"] = value
        return self

    def stack_options(self, opts: "StackOptions") -> "SyncRepositoryBuilder":
        """Copy all fields from a StackOptions into the builder.

        .. deprecated::
            Use individual builder methods instead. This method exists
            to ease migration from the old ``SyncRepository(stack_options=...)``
            pattern.
        """
        warnings.warn(
            "SyncRepositoryBuilder.stack_options() is deprecated. Use individual builder methods (e.g., .lambda_memory(512)) instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        import dataclasses

        for f in dataclasses.fields(opts):
            self._infra_options[f.name] = getattr(opts, f.name)
        return self

    def parallel_mode(self, value: str) -> "SyncRepositoryBuilder":
        """Set parallel execution strategy for cascade writes ("auto", "gevent", "threadpool", "serial")."""
        self._parallel_mode = value
        return self

    def build(self) -> "SyncRepository":
        """Perform initialization and return a fully initialized SyncRepository.

        Steps:
            1. Construct SyncRepository with materialized StackOptions (if any infra options set)
            2. Ensure infrastructure exists (no-op if no infra options)
            3. Register the "default" namespace (conditional PutItem, no-op if exists)
            4. Resolve the requested namespace name to an opaque ID
            5. Reinitialize config cache with resolved namespace ID
            6. Version check and Lambda auto-update (skip for local endpoints)
            7. Return fully initialized SyncRepository

        Raises:
            NamespaceNotFoundError: If the requested namespace doesn't exist
            IncompatibleSchemaError: If schema migration is required
            VersionMismatchError: If auto_update is False and versions differ
        """
        from .models import StackOptions as StackOptionsModel
        from .sync_repository import SyncRepository

        stack_opts = StackOptionsModel(**self._infra_options) if self._infra_options else None
        repo = SyncRepository(
            name=self._name,
            region=self._region,
            endpoint_url=self._endpoint_url,
            stack_options=stack_opts,
            config_cache_ttl=self._config_cache_ttl,
            parallel_mode=self._parallel_mode,
        )
        repo._bucket_ttl_refill_multiplier = self._bucket_ttl_multiplier
        repo._auto_update = self._auto_update
        repo._ensure_infrastructure_internal()
        repo._register_namespace("default")
        namespace_id = repo._resolve_namespace(self._namespace_name)
        if namespace_id is None:
            raise NamespaceNotFoundError(self._namespace_name)
        repo._namespace_id = namespace_id
        repo._namespace_name = self._namespace_name
        repo._reinitialize_config_cache(namespace_id)
        if self._on_unavailable is not None:
            existing_limits, _ = repo.get_system_defaults()
            repo.set_system_defaults(limits=existing_limits, on_unavailable=self._on_unavailable)
        if not self._endpoint_url:
            if self._auto_update:
                repo._check_and_update_version_auto()
            else:
                repo._check_version_strict()
        repo._builder_initialized = True
        return repo
