name: Task
description: A specific piece of work (documentation, testing, etc.)
title: "📋 "
type: Task
labels: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know this is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which component does this relate to?
      options:
        - area/limiter
        - area/cli
        - area/infra
        - area/aggregator
        - area/ci
        - Documentation
        - Testing
        - Unknown
    validations:
      required: false
