"""AUTO-GENERATED by scripts/generate_sync.py - DO NOT EDIT.

Source: test_multi_resource_acquire.py

This module provides synchronous versions of the async classes.
Changes should be made to the source file, then regenerated.
"""

import sys
import warnings

import pytest

from zae_limiter import (
    LeaseExpiredError,
    OnUnavailable,
    RateLimiterUnavailable,
    RateLimitExceeded,
    ResourceDisabled,
    SyncRateLimiter,
    SyncRepository,
    ValidationError,
    __version__,
)
from zae_limiter.models import Limit, QuotaDonorDebit
from zae_limiter.sync_lease import LeaseEntry, QuotaMoveLostError, SyncLease
from zae_limiter.version import get_schema_version

SLOW = dict(refill_amount=1, refill_period_seconds=3600)


@pytest.fixture
def repo(mock_dynamodb):
    r = SyncRepository(
        name="test-multi-resource",
        region="us-east-1",
        rejection_cache_ttl=0,
        _skip_deprecation_warning=True,
    )
    r.create_table()
    r.set_version_record(schema_version=get_schema_version(), lambda_version=__version__)
    r.set_resource_defaults("search", [Limit.custom("rpm", 100, **SLOW)])
    r.set_resource_defaults("budget", [Limit.custom("weekly", 1000, **SLOW)])
    r.set_resource_cascade("budget", False)
    r.create_entity("org", parent_id=None, name="org")
    r.create_entity("user", parent_id="org", name="user", cascade=True)
    yield r
    r.close()


def _consumed(repo, entity_id, resource):
    """Net consumption per limit, summed over every shard."""
    totals: dict[str, int] = {}
    for bucket in repo.get_buckets(entity_id, resource=resource):
        totals[bucket.limit_name] = (
            totals.get(bucket.limit_name, 0) + (bucket.total_consumed_milli or 0) // 1000
        )
    return totals


def _ledger(repo):
    return (
        _consumed(repo, "user", "search"),
        _consumed(repo, "org", "search"),
        _consumed(repo, "user", "budget"),
        _consumed(repo, "org", "budget"),
    )


def _admit(sync_limiter, rpm=1, weekly=10):
    with sync_limiter.acquire(
        "user", "search", {"rpm": rpm}, also={"budget": {"weekly": weekly}}
    ) as lease:
        return lease


@pytest.mark.parametrize("speculative", [True, False])
class TestAllAdmitted:
    def test_every_resource_is_debited_and_only_search_cascades(self, repo, speculative):
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        for _ in range(2):
            lease = _admit(limiter)
        assert lease.resources == ("search", "budget")
        assert lease.consumed == {"rpm": 2}
        assert lease.resource("search").consumed == {"rpm": 2}
        assert lease.resource("budget").consumed == {"weekly": 10}
        assert lease.resource("budget").name == "budget"
        assert repr(lease.resource("budget")).endswith("('budget')")
        assert _ledger(repo) == ({"rpm": 2}, {"rpm": 2}, {"weekly": 20}, {})

    def test_each_resource_reconciles_on_exit(self, repo, speculative):
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        for _ in range(2):
            with limiter.acquire(
                "user", "search", {"rpm": 1}, also={"budget": {"weekly": 10}}
            ) as lease:
                lease.adjust(rpm=2)
                budget = lease.resource("budget")
                budget.adjust(weekly=5)
                budget.consume(weekly=1)
                budget.release(weekly=2)
        assert _ledger(repo) == ({"rpm": 6}, {"rpm": 6}, {"weekly": 28}, {})

    def test_an_exception_in_the_body_refunds_every_resource(self, repo, speculative):
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        _admit(limiter)
        before = _ledger(repo)
        with pytest.raises(RuntimeError, match="boom"):
            with limiter.acquire(
                "user", "search", {"rpm": 1}, also={"budget": {"weekly": 10}}
            ) as lease:
                lease.resource("budget").adjust(weekly=5)
                raise RuntimeError("boom")
        assert _ledger(repo) == before
        with pytest.raises(LeaseExpiredError):
            lease.resource("budget").adjust(weekly=1)
        with pytest.raises(LeaseExpiredError):
            lease.adjust(rpm=1)

    def test_two_resources_may_declare_the_same_limit_name(self, repo, speculative):
        repo.set_resource_defaults("images", [Limit.custom("rpm", 100, **SLOW)])
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        for _ in range(2):
            with limiter.acquire(
                "user", "search", {"rpm": 1}, also={"images": {"rpm": 3}}
            ) as lease:
                lease.adjust(rpm=1)
                lease.resource("images").adjust(rpm=1)
                assert lease.consumed == {"rpm": 4}
                assert lease.resource("images").consumed == {"rpm": 8}
        assert _consumed(repo, "user", "images") == {"rpm": 8}
        assert _consumed(repo, "user", "search") == {"rpm": 4}


@pytest.mark.parametrize("speculative", [True, False])
class TestAllOrNone:
    def test_a_rejected_resource_refunds_the_admitted_one(self, repo, speculative):
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        _admit(limiter)
        before = _ledger(repo)
        with pytest.raises(RateLimitExceeded) as exc_info:
            _admit(limiter, weekly=5000)
        assert _ledger(repo) == before
        violations = {(s.resource, s.limit_name) for s in exc_info.value.violations}
        assert violations == {("budget", "weekly")}
        assert {s["resource"] for s in exc_info.value.as_dict()["limits"]} >= {"budget"}

    def test_a_disabled_resource_refunds_the_admitted_one(self, repo, speculative):
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        _admit(limiter)
        before = _ledger(repo)
        repo.disable_resource("budget")
        with pytest.raises(ResourceDisabled) as exc_info:
            _admit(limiter)
        assert exc_info.value.resource == "budget"
        assert _ledger(repo) == before

    def test_disabled_outranks_rejected(self, repo, speculative):
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        _admit(limiter)
        repo.disable_resource("budget")
        with pytest.raises(ResourceDisabled):
            _admit(limiter, rpm=500)

    def test_a_backend_error_refunds_and_blocks(self, repo, speculative):
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        _admit(limiter)
        before = _ledger(repo)
        _fail_budget(repo, speculative)
        with pytest.raises(RateLimiterUnavailable) as exc_info:
            _admit(limiter)
        assert exc_info.value.resource == "search"
        assert _ledger(repo) == before

    def test_a_backend_error_degrades_under_allow(self, repo, speculative):
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        _admit(limiter)
        before = _ledger(repo)
        _fail_budget(repo, speculative)
        with limiter.acquire(
            "user",
            "search",
            {"rpm": 1},
            on_unavailable=OnUnavailable.ALLOW,
            also={"budget": {"weekly": 10}},
        ) as lease:
            assert lease.degraded
            lease.resource("budget").adjust(weekly=5)
            lease.resource("anything").adjust(weekly=5)
            assert lease.resource("budget").consumed == {}
        assert _ledger(repo) == before


def _fail_budget(repo, speculative):
    """Make every DynamoDB call touching the budget resource fail."""
    if speculative:
        real = repo.speculative_consume

        def speculative_consume(entity_id, resource, consume, *args, **kwargs):
            if resource == "budget":
                raise RuntimeError("throttled")
            return real(entity_id, resource, consume, *args, **kwargs)

        repo.speculative_consume = speculative_consume
    else:
        real_fetch = repo.batch_get_entity_and_buckets

        def batch_get_entity_and_buckets(entity_id, bucket_keys):
            if any(key[1] == "budget" for key in bucket_keys):
                raise RuntimeError("throttled")
            return real_fetch(entity_id, bucket_keys)

        repo.batch_get_entity_and_buckets = batch_get_entity_and_buckets


class TestFastAndSlowTogether:
    """``search`` admitted on the fast path, ``budget`` sent to the slow path."""

    @staticmethod
    def _budget_needs_the_slow_path(repo, capacity):
        repo.set_limits("user", [Limit.custom("weekly", capacity, **SLOW)], "budget")

    def test_the_fast_win_is_kept_and_the_rest_committed(self, repo):
        limiter = SyncRateLimiter(repository=repo)
        _admit(limiter)
        self._budget_needs_the_slow_path(repo, 1000)
        writes = _count_transactions(repo)
        _admit(limiter)
        assert _ledger(repo) == ({"rpm": 2}, {"rpm": 2}, {"weekly": 20}, {})
        assert writes == [1]

    def test_a_slow_rejection_refunds_the_fast_win(self, repo):
        limiter = SyncRateLimiter(repository=repo)
        with limiter.acquire("user", "search", {"rpm": 1}):
            pass
        with limiter.acquire("user", "search", {"rpm": 1}):
            pass
        before = _ledger(repo)
        spent: list[str] = []
        real = repo.speculative_consume

        def speculative_consume(entity_id, resource, *args, **kwargs):
            result = real(entity_id, resource, *args, **kwargs)
            if result.success:
                spent.append(resource)
            return result

        repo.speculative_consume = speculative_consume
        with pytest.raises(RateLimitExceeded) as exc_info:
            _admit(limiter, weekly=5000)
        assert spent == ["search"]
        assert _ledger(repo) == before
        statuses = {(s.resource, s.limit_name, s.exceeded) for s in exc_info.value.statuses}
        assert ("budget", "weekly", True) in statuses
        assert ("search", "rpm", False) in statuses

    def test_a_slow_backend_error_refunds_the_fast_win(self, repo):
        limiter = SyncRateLimiter(repository=repo)
        _admit(limiter)
        self._budget_needs_the_slow_path(repo, 1000)
        before = _ledger(repo)

        def transact_write(items):
            raise RuntimeError("throttled")

        repo.transact_write = transact_write
        with pytest.raises(RateLimiterUnavailable):
            _admit(limiter)
        assert _ledger(repo) == before


def _count_transactions(repo):
    """Record the item count of every transact_write."""
    counts: list[int] = []
    real = repo.transact_write

    def transact_write(items):
        counts.append(len(items))
        return real(items)

    repo.transact_write = transact_write
    return counts


class TestSlowPathPlanning:
    def test_every_slow_part_commits_in_one_transaction(self, repo):
        limiter = SyncRateLimiter(repository=repo, speculative_writes=False)
        writes = _count_transactions(repo)
        _admit(limiter)
        assert writes == [3]

    def test_a_plan_over_the_item_limit_is_re_planned_without_moves(self, repo, monkeypatch):
        limiter = SyncRateLimiter(repository=repo, speculative_writes=False)
        monkeypatch.setattr(sys.modules[type(limiter).__module__], "_MAX_TRANSACT_ITEMS", 1)
        calls: list[bool] = []
        real = limiter._do_acquire

        def do_acquire(**kwargs):
            calls.append(kwargs["disable_moves"])
            return real(**kwargs)

        limiter._do_acquire = do_acquire
        _admit(limiter)
        assert calls == [False, False, True, True]
        assert _ledger(repo) == ({"rpm": 1}, {"rpm": 1}, {"weekly": 10}, {})

    def test_a_lost_move_re_plans_every_part(self, repo, monkeypatch):
        limiter = SyncRateLimiter(repository=repo, speculative_writes=False)
        real = SyncLease._commit_initial
        losses = [QuotaMoveLostError(), QuotaMoveLostError()]

        def commit_initial(self):
            if losses and len({entry.resource for entry in self.entries}) > 1:
                raise losses.pop()
            return real(self)

        monkeypatch.setattr(SyncLease, "_commit_initial", commit_initial)
        calls: list[bool] = []
        real_do = limiter._do_acquire

        def do_acquire(**kwargs):
            calls.append(kwargs["disable_moves"])
            return real_do(**kwargs)

        limiter._do_acquire = do_acquire
        _admit(limiter)
        assert calls == [False, False, False, False, True, True]
        assert _ledger(repo) == ({"rpm": 1}, {"rpm": 1}, {"weekly": 10}, {})

    def test_a_rejected_part_does_not_lose_another_parts_move(self, repo):
        """ADR-145 I5: a planned move commits with nothing consumed on rejection."""
        limiter = SyncRateLimiter(repository=repo, speculative_writes=False)
        _admit(limiter)
        real = limiter._do_acquire

        def do_acquire(**kwargs):
            lease = real(**kwargs)
            if kwargs["resource"] == "search":
                lease.entries[0]._donor_debit = QuotaDonorDebit(
                    shard_id=1,
                    limit_name="rpm",
                    tokens_milli=1,
                    grant_count=2,
                    guard_rf_ms=None,
                    guard_wa_ms=None,
                )
            return lease

        committed: list[set[str]] = []

        def commit_rejected_moves(entries, carriers):
            committed.append({entry.resource for entry in entries})
            for entry in entries:
                entry.consumed = 0

        limiter._do_acquire = do_acquire
        limiter._commit_rejected_moves = commit_rejected_moves
        with pytest.raises(RateLimitExceeded) as exc_info:
            _admit(limiter, weekly=5000)
        assert committed == [{"search"}]
        search = [s for s in exc_info.value.statuses if s.resource == "search"]
        assert search and all(s.requested == 1 for s in search)


class TestRejectionCache:
    def test_a_resource_known_short_rejects_with_no_write(self, mock_dynamodb):
        repo = SyncRepository(
            name="test-multi-cache", region="us-east-1", _skip_deprecation_warning=True
        )
        repo.create_table()
        repo.set_resource_defaults("search", [Limit.custom("rpm", 100, **SLOW)])
        repo.set_resource_defaults("budget", [Limit.custom("weekly", 20, **SLOW)])
        repo.create_entity("user", parent_id=None, name="user")
        limiter = SyncRateLimiter(repository=repo)
        _admit(limiter, weekly=10)
        _admit(limiter, weekly=10)
        before = (_consumed(repo, "user", "search"), _consumed(repo, "user", "budget"))
        calls: list[str] = []
        real = repo.speculative_consume

        def speculative_consume(entity_id, resource, *args, **kwargs):
            calls.append(resource)
            return real(entity_id, resource, *args, **kwargs)

        repo.speculative_consume = speculative_consume
        with pytest.raises(RateLimitExceeded) as exc_info:
            _admit(limiter, weekly=10)
        assert calls == []
        assert exc_info.value.primary_violation.resource == "budget"
        after = (_consumed(repo, "user", "search"), _consumed(repo, "user", "budget"))
        assert after == before
        repo.close()


class TestValidation:
    @pytest.fixture
    def multi_limiter(self, repo):
        return SyncRateLimiter(repository=repo)

    def test_the_primary_resource_may_not_appear_in_also(self, multi_limiter):
        with pytest.raises(ValidationError, match="primary resource"):
            with multi_limiter.acquire("user", "search", {"rpm": 1}, also={"search": {"rpm": 1}}):
                pass

    def test_too_many_resources(self, multi_limiter):
        also = {f"r{i}": {"rpm": 1} for i in range(16)}
        with pytest.raises(ValidationError, match="at most 16 resources"):
            with multi_limiter.acquire("user", "search", {"rpm": 1}, also=also):
                pass

    def test_limits_cannot_be_combined_with_also(self, multi_limiter):
        with pytest.raises(ValidationError, match="limits="):
            with multi_limiter.acquire(
                "user",
                "search",
                {"rpm": 1},
                limits=[Limit.per_minute("rpm", 10)],
                also={"budget": {"weekly": 1}},
            ):
                pass

    def test_a_bad_resource_name(self, multi_limiter):
        with pytest.raises(ValidationError):
            with multi_limiter.acquire("user", "search", {"rpm": 1}, also={"bad#name": {"x": 1}}):
                pass

    def test_an_empty_also_is_a_single_resource_acquire(self, multi_limiter, repo):
        with multi_limiter.acquire("user", "search", {"rpm": 1}, also={}) as lease:
            assert lease.resources == ("search",)
            with pytest.raises(ValidationError, match="not a resource of this lease"):
                lease.resource("budget")
        assert _consumed(repo, "user", "search") == {"rpm": 1}

    def test_a_handle_for_a_resource_not_in_the_lease(self, multi_limiter):
        with multi_limiter.acquire(
            "user", "search", {"rpm": 1}, also={"budget": {"weekly": 1}}
        ) as lease:
            with pytest.raises(ValidationError, match="not a resource of this lease"):
                lease.resource("images")

    def test_an_undeclared_key_on_a_handle_warns_with_its_resource(self, multi_limiter):
        with multi_limiter.acquire(
            "user", "search", {"rpm": 1}, also={"budget": {"weekly": 1}}
        ) as lease:
            with warnings.catch_warnings(record=True) as caught:
                warnings.simplefilter("always")
                lease.resource("budget").adjust(rpm=1)
        messages = [str(w.message) for w in caught if issubclass(w.category, FutureWarning)]
        assert len(messages) == 1
        assert "lease.resource('budget').adjust()" in messages[0]
        assert "also={'budget': ...}" in messages[0]


class TestLeaseWithoutBoundResources:
    """A lease built without `_bind_resources` keeps its pre-ADR-148 meaning."""

    def test_resources_come_from_its_entries(self):
        entries = [
            LeaseEntry(entity_id="e", resource=name, limit=Limit.per_minute("rpm", 10), state=None)
            for name in ("a", "b", "a")
        ]
        lease = SyncLease(repository=None, entries=entries)
        assert lease.resources == ("a", "b")
        assert lease.consumed == {"rpm": 0}
        assert lease.resource("b").consumed == {"rpm": 0}
