"""AUTO-GENERATED by scripts/generate_sync.py - DO NOT EDIT.

Source: test_zero_estimate_lease.py

This module provides synchronous versions of the async classes.
Changes should be made to the source file, then regenerated.
"""

import warnings

import pytest

from zae_limiter import OnUnavailable, RateLimitExceeded, SyncRateLimiter, SyncRepository, schema
from zae_limiter.models import Limit

SLOW = dict(refill_amount=1, refill_period_seconds=3600)


@pytest.fixture
def repo(mock_dynamodb):
    r = SyncRepository(name="test-zero-est", region="us-east-1", _skip_deprecation_warning=True)
    r.create_table()
    yield r
    r.close()


def _tokens(repo, entity_id, resource):
    buckets = repo.get_buckets(entity_id, resource=resource)
    return {b.limit_name: b.tokens_milli for b in buckets}


@pytest.mark.parametrize("speculative", [True, False])
class TestZeroEstimateIsStillAdjustable:
    def test_second_acquire_persists_the_adjustment(self, repo, speculative):
        """The reported bug: round 1 works, round 2 silently drops the adjust."""
        repo.set_system_defaults([Limit.custom("rpm", 1000, **SLOW)])
        repo.create_entity("e1", parent_id=None, name="e1")
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            for _ in range(2):
                with limiter.acquire("e1", "api", {"rpm": 0}) as lease:
                    lease.adjust(rpm=10)
        assert _tokens(repo, "e1", "api")["rpm"] == 1000000 - 2 * 10000

    def test_zero_estimate_limit_appears_in_lease_consumed(self, repo, speculative):
        repo.set_system_defaults([Limit.custom("rpm", 1000, **SLOW)])
        repo.create_entity("e1", parent_id=None, name="e1")
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            with limiter.acquire("e1", "api", {"rpm": 0}) as lease:
                lease.adjust(rpm=10)
            with limiter.acquire("e1", "api", {"rpm": 0}) as lease:
                lease.adjust(rpm=10)
                second_consumed = dict(lease.consumed)
        assert second_consumed == {"rpm": 10}

    def test_mixed_estimates_both_track(self, repo, speculative):
        """The insidious variant: one limit meters normally, the other freezes."""
        repo.set_system_defaults(
            [Limit.custom("rpm", 1000, **SLOW), Limit.custom("tpm", 1000, **SLOW)]
        )
        repo.create_entity("e1", parent_id=None, name="e1")
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            for _ in range(2):
                with limiter.acquire("e1", "api", {"rpm": 1, "tpm": 0}) as lease:
                    lease.adjust(tpm=10)
        tokens = _tokens(repo, "e1", "api")
        assert tokens["rpm"] == 1000000 - 2 * 1000
        assert tokens["tpm"] == 1000000 - 2 * 10000

    def test_release_on_a_zero_estimate_limit_is_persisted(self, repo, speculative):
        """`release()` is `adjust()` negated, so it was dropped the same way."""
        repo.set_system_defaults([Limit.custom("rpm", 1000, **SLOW)])
        repo.create_entity("e1", parent_id=None, name="e1")
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            with limiter.acquire("e1", "api", {"rpm": 100}) as lease:
                pass
            with limiter.acquire("e1", "api", {"rpm": 0}) as lease:
                lease.consume(rpm=50)
                lease.release(rpm=20)
        assert _tokens(repo, "e1", "api")["rpm"] == 1000000 - 100000 - 30000


@pytest.mark.parametrize("speculative", [True, False])
class TestWcuStaysInternal:
    """The `amount == 0` filter was also, incidentally, hiding `wcu`.

    `result.buckets` on the speculative path comes from
    `_deserialize_composite_bucket()`, which includes the reserved `wcu`
    infrastructure limit — the WCU filtering in `get_buckets` is applied
    separately. Widening the filter must not leak `wcu` to callers.
    """

    def test_wcu_absent_from_lease_consumed(self, repo, speculative):
        repo.set_system_defaults([Limit.custom("rpm", 1000, **SLOW)])
        repo.create_entity("e1", parent_id=None, name="e1")
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            with limiter.acquire("e1", "api", {"rpm": 1}):
                pass
            with limiter.acquire("e1", "api", {"rpm": 1}) as lease:
                lease.adjust(rpm=1)
                assert schema.WCU_LIMIT_NAME not in lease.consumed
                assert all(e.limit.name != schema.WCU_LIMIT_NAME for e in lease.entries)

    def test_adjusting_wcu_from_the_lease_is_reported_and_ignored(self, repo, speculative):
        """`wcu` is never in `consume`, so adjusting it is an undeclared-key
        adjustment like any other (#455): warned about and not applied."""
        repo.set_system_defaults([Limit.custom("rpm", 1000, **SLOW)])
        repo.create_entity("e1", parent_id=None, name="e1")
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            with limiter.acquire("e1", "api", {"rpm": 1}):
                pass
            with limiter.acquire("e1", "api", {"rpm": 1}) as lease:
                with pytest.warns(FutureWarning, match=schema.WCU_LIMIT_NAME):
                    lease.adjust(**{schema.WCU_LIMIT_NAME: 500})
                assert lease.consumed.get(schema.WCU_LIMIT_NAME) is None
        buckets = repo.get_buckets("e1", resource="api")
        assert all(b.limit_name != schema.WCU_LIMIT_NAME for b in buckets), (
            "get_buckets filters wcu; the adjust above must not have leaked it"
        )


@pytest.mark.parametrize("speculative", [True, False])
class TestUndeclaredLimitIsReported:
    """`consume` is the declared scope of a lease (#455).

    A limit the caller did not name in `acquire(consume=...)` was never
    checked at admission, so adjusting it afterwards would drive a bucket
    negative that never had the chance to reject. Both paths must therefore
    treat such a key the same way: report it and leave the bucket alone.

    Staged rollout: `FutureWarning` now, `ValidationError` at v1.0.0.
    """

    def _rpm_and_tpm(self, repo):
        repo.set_system_defaults(
            [Limit.custom("rpm", 1000, **SLOW), Limit.custom("tpm", 1000, **SLOW)]
        )
        repo.create_entity("e1", parent_id=None, name="e1")

    def test_adjust_on_undeclared_limit_warns_and_is_not_applied(self, repo, speculative):
        """The reported divergence: the first acquire (slow path) used to
        apply `adjust(tpm=...)` for a `tpm` never in `consume`; later acquires
        (fast path) dropped it silently. Now both warn and neither applies."""
        self._rpm_and_tpm(repo)
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            for _ in range(2):
                with limiter.acquire("e1", "api", {"rpm": 1}) as lease:
                    with pytest.warns(FutureWarning, match="'tpm'"):
                        lease.adjust(tpm=100)
        tokens = _tokens(repo, "e1", "api")
        assert tokens["rpm"] == 1000000 - 2 * 1000
        assert tokens["tpm"] == 1000000, "tpm was never declared; it must be untouched"

    def test_typo_key_warns_and_names_the_declared_limits(self, repo, speculative):
        """`adjust(tpmm=...)` where `tpm` is the real limit: the warning must
        name the offending key, the declared limits, and the v1.0.0 error."""
        self._rpm_and_tpm(repo)
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            for _ in range(2):
                with limiter.acquire("e1", "api", {"rpm": 1, "tpm": 500}) as lease:
                    with pytest.warns(FutureWarning) as record:
                        lease.adjust(tpmm=100)
        assert len(record) == 1
        message = str(record[0].message)
        assert "'tpmm'" in message
        assert "'rpm'" in message and "'tpm'" in message
        assert "ValidationError" in message and "v1.0.0" in message
        assert record[0].filename == __file__
        assert _tokens(repo, "e1", "api")["tpm"] == 1000000 - 2 * 500000

    def test_consume_on_undeclared_limit_warns_and_is_not_applied(self, repo, speculative):
        self._rpm_and_tpm(repo)
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            for _ in range(2):
                with limiter.acquire("e1", "api", {"rpm": 1}) as lease:
                    with pytest.warns(FutureWarning, match="consume\\(\\).*'tpm'"):
                        lease.consume(tpm=100)
                    assert "tpm" not in lease.consumed
        assert _tokens(repo, "e1", "api")["tpm"] == 1000000

    def test_release_on_undeclared_limit_warns_and_is_not_applied(self, repo, speculative):
        self._rpm_and_tpm(repo)
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            for _ in range(2):
                with limiter.acquire("e1", "api", {"rpm": 1}) as lease:
                    with pytest.warns(FutureWarning, match="release\\(\\).*'tpm'"):
                        lease.release(tpm=100)
        assert _tokens(repo, "e1", "api")["tpm"] == 1000000

    def test_declared_zero_estimate_never_warns(self, repo, speculative):
        """`{"tpm": 0}` is a real declaration (#453); it must stay warning-free."""
        self._rpm_and_tpm(repo)
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            for _ in range(2):
                with limiter.acquire("e1", "api", {"rpm": 1, "tpm": 0}) as lease:
                    with warnings.catch_warnings():
                        warnings.simplefilter("error", FutureWarning)
                        lease.adjust(tpm=100)
                        lease.consume(tpm=1)
                        lease.release(tpm=1)
        assert _tokens(repo, "e1", "api")["tpm"] == 1000000 - 2 * 100000

    def test_lease_consumed_reports_only_declared_limits(self, repo, speculative):
        """The slow path used to report `{"rpm": 1, "tpm": 0}`; the fast path
        `{"rpm": 1}`. The declared scope is the same on both."""
        self._rpm_and_tpm(repo)
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            for _ in range(2):
                with limiter.acquire("e1", "api", {"rpm": 1}) as lease:
                    assert lease.consumed == {"rpm": 1}

    def test_slow_path_still_persists_every_configured_limit(self, repo, speculative):
        """Guard for the design constraint behind #455: the slow path's write
        must still carry every resolved limit, not just the declared ones.
        `build_composite_create` writes only the states it is handed, and
        `build_composite_normal` advances the shared `rf` while crediting
        refill only to the limits it is handed — so narrowing the *write* to
        `consume` would create buckets without `tpm` and lose `tpm` refill on
        every `rpm`-only acquire. Only the lease's *adjustable scope* narrows."""
        self._rpm_and_tpm(repo)
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            with limiter.acquire("e1", "api", {"rpm": 1}):
                pass
        tokens = _tokens(repo, "e1", "api")
        assert tokens == {"rpm": 1000000 - 1000, "tpm": 1000000}


@pytest.mark.parametrize("speculative", [True, False])
class TestDeclaredLimitsGateAdmission:
    """Only declared limits gate admission and appear in RateLimitExceeded.

    The fast path's conditional UpdateItem covers only the limits in
    `consume`, so an undeclared limit in debt never rejects there. The slow
    path used to run `try_consume(state, 0, now)` for every resolved limit,
    and a bucket in debt fails that check even for a request of 0 — so an
    rpm-only acquire was REJECTED on the slow path but ADMITTED on the fast
    path. Both paths must agree: undeclared limits are refilled (they are
    still written) but never checked and never reported.
    """

    def _rpm_and_tpm(self, repo, rpm_capacity=1000):
        repo.set_system_defaults(
            [Limit.custom("rpm", rpm_capacity, **SLOW), Limit.custom("tpm", 1000, **SLOW)]
        )
        repo.create_entity("e1", parent_id=None, name="e1")

    def test_undeclared_limit_in_debt_does_not_reject(self, repo, speculative):
        self._rpm_and_tpm(repo)
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            with limiter.acquire("e1", "api", {"rpm": 1, "tpm": 0}) as lease:
                lease.adjust(tpm=2000)
            for _ in range(2):
                with limiter.acquire("e1", "api", {"rpm": 1}):
                    pass
        tokens = _tokens(repo, "e1", "api")
        assert tokens["tpm"] == -1000000, "tpm is in debt and must stay untouched"
        assert tokens["rpm"] == 1000000 - 3 * 1000

    def test_acquire_rejection_lists_only_declared_limits(self, repo, speculative):
        self._rpm_and_tpm(repo, rpm_capacity=1)
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            with limiter.acquire("e1", "api", {"rpm": 0}):
                pass
            with pytest.raises(RateLimitExceeded) as exc_info:
                with limiter.acquire("e1", "api", {"rpm": 5}):
                    pass
        exc = exc_info.value
        assert {s.limit_name for s in exc.statuses} == {"rpm"}
        assert {s.limit_name for s in exc.violations} == {"rpm"}
        assert exc.passed == []

    def test_rejection_includes_declared_zero_estimate_limits(self, repo, speculative):
        """`{"rpm": 5, "tpm": 0}` rejected on rpm: the fast-reject path used
        to skip tpm because its amount was 0, while the slow path reported it
        as passed with requested=0. Declared is declared on both paths."""
        self._rpm_and_tpm(repo, rpm_capacity=1)
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            with limiter.acquire("e1", "api", {"rpm": 0, "tpm": 0}):
                pass
            with pytest.raises(RateLimitExceeded) as exc_info:
                with limiter.acquire("e1", "api", {"rpm": 5, "tpm": 0}):
                    pass
        exc = exc_info.value
        assert {s.limit_name for s in exc.statuses} == {"rpm", "tpm"}
        assert {s.limit_name for s in exc.violations} == {"rpm"}
        (tpm,) = exc.passed
        assert tpm.limit_name == "tpm" and tpm.requested == 0

    def test_cascade_rejection_lists_only_declared_limits(self, repo, speculative):
        """The cascade fast-reject sites build child statuses from every
        bucket in the speculative result, which carries the reserved `wcu`
        limit and any undeclared limit. Neither may leak."""
        repo.set_system_defaults(
            [Limit.custom("rpm", 2, **SLOW), Limit.custom("tpm", 1000, **SLOW)]
        )
        repo.create_entity("parent", parent_id=None, name="parent")
        repo.create_entity("child", parent_id="parent", name="child", cascade=True)
        repo.set_limits(
            "child",
            [Limit.custom("rpm", 100, **SLOW), Limit.custom("tpm", 1000, **SLOW)],
            resource="api",
        )
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            for _ in range(2):
                with limiter.acquire("child", "api", {"rpm": 1}):
                    pass
            with pytest.raises(RateLimitExceeded) as exc_info:
                with limiter.acquire("child", "api", {"rpm": 1}):
                    pass
        exc = exc_info.value
        assert {s.limit_name for s in exc.statuses} == {"rpm"}
        assert {(s.entity_id, s.limit_name) for s in exc.violations} == {("parent", "rpm")}

    def test_empty_consume_declares_nothing(self, repo, speculative):
        """On main the slow path built declared entries for every resolved
        limit, so `consume={}` then `adjust(tpm=...)` worked on the first
        call only. An empty `consume` declares nothing on either path."""
        self._rpm_and_tpm(repo)
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            for _ in range(2):
                with limiter.acquire("e1", "api", {}) as lease:
                    assert lease.consumed == {}
                    with pytest.warns(FutureWarning) as record:
                        lease.adjust(tpm=1200)
                    assert "'tpm'" in str(record[0].message)
                    assert "declared limits on this lease: []" in str(record[0].message)
        tokens = _tokens(repo, "e1", "api")
        assert tokens == {"rpm": 1000000, "tpm": 1000000}, "nothing was consumed"


@pytest.mark.parametrize("speculative", [True, False])
class TestUnknownLimitInConsume:
    """A key in `consume` that names no configured limit is silently dropped
    at admission (`consume.get(limit.name, 0)`), after which every
    `adjust()` on it warns "not declared in consume" — pointing at the wrong
    fix, since the caller did declare it. Close it where the declaration is
    made: `acquire()` warns that the key is not configured for the resource.

    The fast path cannot see this (an unknown key makes `speculative_consume`
    fail and fall back), so the slow-path check covers both paths.
    """

    def test_unknown_key_warns_at_acquire_and_gets_no_entry(self, repo, speculative):
        repo.set_system_defaults([Limit.custom("rpm", 1000, **SLOW)])
        repo.create_entity("e1", parent_id=None, name="e1")
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            for _ in range(2):
                with pytest.warns(FutureWarning) as record:
                    with limiter.acquire("e1", "api", {"rpm": 1, "tpm": 500}) as lease:
                        assert {e.limit.name for e in lease.entries} == {"rpm"}
                        assert lease.consumed == {"rpm": 1}
                acquire_warnings = [w for w in record if "acquire()" in str(w.message)]
                assert len(acquire_warnings) == 1
                message = str(acquire_warnings[0].message)
                assert "'tpm'" in message and "not configured" in message
                assert "'rpm'" in message
                assert "ValidationError" in message and "v1.0.0" in message
                assert "e1" not in message and "api" not in message
                assert acquire_warnings[0].filename == __file__
        assert _tokens(repo, "e1", "api")["rpm"] == 1000000 - 2 * 1000

    @pytest.mark.parametrize("mode", [OnUnavailable.BLOCK, OnUnavailable.ALLOW])
    def test_warning_as_error_propagates_instead_of_degrading(self, repo, speculative, mode):
        """The unknown-key check runs inside acquire()'s outage handler. Under
        warnings-as-errors the raised FutureWarning must propagate as itself —
        not be classified as a backend outage and turned into
        RateLimiterUnavailable (BLOCK) or a silent degraded lease (ALLOW)."""
        repo.set_system_defaults([Limit.custom("rpm", 1000, **SLOW)])
        repo.create_entity("e1", parent_id=None, name="e1")
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            with warnings.catch_warnings():
                warnings.simplefilter("error", FutureWarning)
                with pytest.raises(FutureWarning):
                    with limiter.acquire("e1", "api", {"rpm": 1, "tpmm": 5}, on_unavailable=mode):
                        pytest.fail("acquire() must not yield a lease")

    def test_child_with_subset_of_parent_limits_does_not_warn(self, repo, speculative):
        """Entity config replaces rather than merges: a child pinned to
        `[rpm]` cascading to a parent on `[rpm, tpm]` still has `tpm` gated
        and consumed on the parent. "Org-level tpm budget on the parent,
        per-user rpm on the child" is a legitimate configuration, so a key
        known to either side of the cascade must not warn."""
        repo.set_system_defaults(
            [Limit.custom("rpm", 1000, **SLOW), Limit.custom("tpm", 1000, **SLOW)]
        )
        repo.create_entity("parent", parent_id=None, name="parent")
        repo.create_entity("child", parent_id="parent", name="child", cascade=True)
        repo.set_limits("child", [Limit.custom("rpm", 1000, **SLOW)], resource="api")
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            with warnings.catch_warnings():
                warnings.simplefilter("error", FutureWarning)
                for _ in range(2):
                    with limiter.acquire("child", "api", {"rpm": 1, "tpm": 100}) as lease:
                        assert lease.consumed == {"rpm": 2, "tpm": 100}
        assert "tpm" not in _tokens(repo, "child", "api")
        assert _tokens(repo, "parent", "api")["tpm"] == 1000000 - 2 * 100000

    def _parent_rpm_only_child_rpm_tpm(self, repo):
        """Parent tracks rpm only; the cascading child tracks rpm + tpm."""
        repo.set_system_defaults(
            [Limit.custom("rpm", 1000, **SLOW), Limit.custom("tpm", 1000, **SLOW)]
        )
        repo.create_entity("parent", parent_id=None, name="parent")
        repo.create_entity("child", parent_id="parent", name="child", cascade=True)
        repo.set_limits("parent", [Limit.custom("rpm", 1000, **SLOW)], resource="api")

    def test_parent_with_subset_of_child_limits_does_not_warn(self, repo, speculative):
        """The declaration is about the entity being acquired on. A cascade
        parent tracking a subset of the child's limits is a legitimate
        configuration: keys with no parent limit are silently not applied to
        the parent, and nothing warns."""
        self._parent_rpm_only_child_rpm_tpm(repo)
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            with warnings.catch_warnings():
                warnings.simplefilter("error", FutureWarning)
                for _ in range(2):
                    with limiter.acquire("child", "api", {"rpm": 1, "tpm": 100}) as lease:
                        assert lease.consumed == {"rpm": 2, "tpm": 100}
        assert _tokens(repo, "child", "api")["tpm"] == 1000000 - 2 * 100000
        parent_tokens = _tokens(repo, "parent", "api")
        assert "tpm" not in parent_tokens
        assert parent_tokens["rpm"] == 1000000 - 2 * 1000

    def test_parent_only_path_does_not_warn_on_parent_subset(self, repo, speculative, monkeypatch):
        """Same configuration, forced through the parent-only slow path: the
        child's speculative write succeeds and the parent's fails with buckets
        that cover every consumed name (a stale tpm bucket) and refill would
        help. The parent's resolved limits are rpm only; no warning."""
        import time

        from zae_limiter.models import BucketState
        from zae_limiter.sync_repository_protocol import SpeculativeResult

        self._parent_rpm_only_child_rpm_tpm(repo)
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            with limiter.acquire("child", "api", {"rpm": 1, "tpm": 100}):
                pass
            limiter._speculative_writes = True
            now_ms = int(time.time() * 1000)

            def bucket(entity_id, name, tokens_milli, last_refill_ms):
                return BucketState(
                    entity_id=entity_id,
                    resource="api",
                    limit_name=name,
                    tokens_milli=tokens_milli,
                    last_refill_ms=last_refill_ms,
                    capacity_milli=1000000,
                    refill_amount_milli=1000000,
                    refill_period_ms=60000,
                )

            original = repo.speculative_consume
            calls = 0

            def mock_speculative(entity_id, resource, consume, ttl_seconds=None, **kw):
                nonlocal calls
                calls += 1
                if calls == 1:
                    return SpeculativeResult(
                        success=True,
                        buckets=[
                            bucket("child", "rpm", 900000, now_ms),
                            bucket("child", "tpm", 800000, now_ms),
                        ],
                        cascade=True,
                        parent_id="parent",
                    )
                if calls == 2:
                    return SpeculativeResult(
                        success=False,
                        old_buckets=[
                            bucket("parent", "rpm", 0, now_ms - 30000),
                            bucket("parent", "tpm", 0, now_ms - 30000),
                        ],
                    )
                return original(entity_id, resource, consume, ttl_seconds, **kw)

            monkeypatch.setattr(repo, "speculative_consume", mock_speculative)
            with warnings.catch_warnings():
                warnings.simplefilter("error", FutureWarning)
                with limiter.acquire("child", "api", {"rpm": 1, "tpm": 100}) as lease:
                    parent_entries = [e for e in lease.entries if e.entity_id == "parent"]
                    assert {e.limit.name for e in parent_entries} == {"rpm"}
            assert calls == 2, "the parent-only slow path must have been taken"

    def test_typo_key_with_parent_subset_still_warns_once(self, repo, speculative):
        self._parent_rpm_only_child_rpm_tpm(repo)
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            for _ in range(2):
                with pytest.warns(FutureWarning) as record:
                    with limiter.acquire("child", "api", {"rpm": 1, "tpmm": 5}):
                        pass
                acquire_warnings = [w for w in record if "acquire()" in str(w.message)]
                assert len(acquire_warnings) == 1
                assert "'tpmm'" in str(acquire_warnings[0].message)
                assert "child" not in str(acquire_warnings[0].message)
                assert acquire_warnings[0].filename == __file__

    def test_acquire_time_unknown_key_is_not_reported_again_on_adjust(self, repo, speculative):
        """acquire() already reported the key with the right advice. A later
        adjust() on it must not warn a second time with the wrong advice
        ("name the limit in consume" — the caller did)."""
        repo.set_system_defaults([Limit.custom("rpm", 1000, **SLOW)])
        repo.create_entity("e1", parent_id=None, name="e1")
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            for _ in range(2):
                with pytest.warns(FutureWarning) as record:
                    with limiter.acquire("e1", "api", {"rpm": 1, "tpmm": 5}) as lease:
                        lease.adjust(tpmm=3)
                        lease.consume(tpmm=1)
                        lease.release(tpmm=1)
                future = [w for w in record if issubclass(w.category, FutureWarning)]
                assert len(future) == 1, [str(w.message) for w in future]
                assert "acquire()" in str(future[0].message)

    def test_message_is_identical_across_entities(self, repo, speculative, caplog):
        """The text must not vary per entity, or every entity adds a
        __warningregistry__ entry and defeats the default once-per-location
        filter (a warning storm). Entity and resource go to the log."""
        import logging

        repo.set_system_defaults([Limit.custom("rpm", 1000, **SLOW)])
        for eid in ("e1", "e2"):
            repo.create_entity(eid, parent_id=None, name=eid)
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        messages = []
        with limiter:
            with caplog.at_level(logging.WARNING, logger="zae_limiter.sync_limiter"):
                for eid in ("e1", "e2"):
                    with pytest.warns(FutureWarning) as record:
                        with limiter.acquire(eid, "api", {"rpm": 1, "tpmm": 5}):
                            pass
                    messages.append(
                        next(str(w.message) for w in record if "acquire()" in str(w.message))
                    )
        assert messages[0] == messages[1]
        logged = [r.getMessage() for r in caplog.records if "tpmm" in r.getMessage()]
        assert len(logged) == 2
        assert all("api" in m for m in logged)
        assert not any("e1" in m or "e2" in m for m in logged)

    def test_override_wording_when_limits_passed(self, repo, speculative):
        """`limits=[...]` replaces stored config for this call, so "not
        configured for this resource" would be false when the key exists in
        stored config. Say what was actually checked: the override."""
        repo.set_system_defaults(
            [Limit.custom("rpm", 1000, **SLOW), Limit.custom("tpm", 1000, **SLOW)]
        )
        repo.create_entity("e1", parent_id=None, name="e1")
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            for _ in range(2):
                with pytest.warns(FutureWarning) as record:
                    with limiter.acquire(
                        "e1",
                        "api",
                        {"rpm": 1, "tpm": 5},
                        limits=[Limit.custom("rpm", 1000, **SLOW)],
                    ):
                        pass
                message = next(str(w.message) for w in record if "acquire()" in str(w.message))
                assert "'tpm'" in message
                assert "`limits` override passed to acquire()" in message
                assert "not configured" not in message
                assert "override limits: ['rpm']" in message


@pytest.mark.parametrize("speculative", [True, False])
class TestDegradedLeaseIsExempt:
    """Under `on_unavailable=ALLOW`, an outage yields a degraded lease with no
    entries. Declared-scope validation must not turn that degradation into a
    warning storm (or, at v1.0.0, a failure): the lease is marked `degraded`
    explicitly rather than inferred from `entries == []`."""

    @staticmethod
    def _simulate_outage(repo, monkeypatch):
        from botocore.exceptions import ClientError

        def down(*args, **kwargs):
            raise ClientError(
                {"Error": {"Code": "ServiceUnavailable", "Message": "DynamoDB down"}}, "UpdateItem"
            )

        monkeypatch.setattr(repo, "speculative_consume", down)
        monkeypatch.setattr(repo, "batch_get_entity_and_buckets", down)

    def test_adjust_consume_release_never_warn_on_degraded_lease(
        self, repo, speculative, monkeypatch
    ):
        repo.set_system_defaults([Limit.custom("rpm", 1000, **SLOW)])
        self._simulate_outage(repo, monkeypatch)
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            with limiter.acquire(
                "e1", "api", {"rpm": 1}, on_unavailable=OnUnavailable.ALLOW
            ) as lease:
                assert lease.degraded is True
                assert lease.entries == []
                with warnings.catch_warnings():
                    warnings.simplefilter("error", FutureWarning)
                    lease.adjust(rpm=100, tpm=100)
                    lease.consume(rpm=1)
                    lease.release(rpm=1)
                assert lease.consumed == {}

    def test_real_lease_is_not_degraded(self, repo, speculative):
        repo.set_system_defaults([Limit.custom("rpm", 1000, **SLOW)])
        repo.create_entity("e1", parent_id=None, name="e1")
        limiter = SyncRateLimiter(repository=repo, speculative_writes=speculative)
        with limiter:
            for _ in range(2):
                with limiter.acquire("e1", "api", {"rpm": 1}) as lease:
                    assert lease.degraded is False


class TestShardRetryLeaseIsUsable:
    """A lease from the shard-retry path must behave like any other lease.

    `_build_lease_from_speculative()` returns the lease used when the
    selected shard is exhausted and another shard serves the request. Unlike
    its sibling — which sets `_initial_committed` and seeds each entry's
    `_initial_consumed` — it was born `_committed=True`, and both
    `SyncLease.adjust()` and `SyncLease._rollback()` short-circuit on that flag. So
    adjustments raised `LeaseExpiredError` instead of reconciling, and an
    exception in the caller's body skipped compensation entirely, leaving
    tokens the speculative UpdateItem had already consumed unreturned.

    Setting `_initial_committed` alone is not enough: `_initial_consumed`
    must be seeded too, or `_commit_adjustments()` re-writes the initial
    consumption as a delta and double-counts it.
    """

    @staticmethod
    def _two_shards_first_exhausted(sync_limiter, monkeypatch):
        """Two shards, rpm exhausted on shard 0, selection pinned to shard 0."""
        import random as _random
        import time

        from zae_limiter import repository as _repo_mod
        from zae_limiter.models import BucketState

        repo = sync_limiter._repository
        ns = repo._namespace_id
        limit = Limit.custom("rpm", 10, **SLOW)
        sync_limiter.create_entity("user-1")
        sync_limiter.set_system_defaults([limit])
        now_ms = int(time.time() * 1000)
        for shard_id in (0, 1):
            states = [BucketState.from_limit("user-1", "gpt-4", limit, now_ms)]
            repo.transact_write(
                [
                    repo.build_composite_create(
                        "user-1", "gpt-4", states, now_ms, shard_id=shard_id, shard_count=2
                    )
                ]
            )
        repo._entity_cache[ns, "user-1"] = (False, None, {"gpt-4": 2})
        repo._speculative_consume_single("user-1", "gpt-4", {"rpm": 10}, shard_id=0)
        monkeypatch.setattr(_repo_mod.random, "randrange", lambda _n: 0)
        monkeypatch.setattr(_random, "choice", lambda seq: seq[0])
        sync_limiter._speculative_writes = True
        return repo

    def test_adjust_after_shard_retry_is_persisted(self, sync_limiter, monkeypatch):
        repo = self._two_shards_first_exhausted(sync_limiter, monkeypatch)
        with sync_limiter.acquire("user-1", "gpt-4", {"rpm": 10}) as lease:
            lease.adjust(rpm=5)
        buckets = repo.get_buckets("user-1", resource="gpt-4", shard_id=1)
        rpm = next(b for b in buckets if b.limit_name == "rpm")
        assert rpm.tokens_milli == 10000 - 10000 - 5000

    def test_shard_retry_lease_rolls_back_on_exception(self, sync_limiter, monkeypatch):
        repo = self._two_shards_first_exhausted(sync_limiter, monkeypatch)
        with pytest.raises(RuntimeError):
            with sync_limiter.acquire("user-1", "gpt-4", {"rpm": 10}):
                raise RuntimeError("caller blew up")
        buckets = repo.get_buckets("user-1", resource="gpt-4", shard_id=1)
        rpm = next(b for b in buckets if b.limit_name == "rpm")
        assert rpm.tokens_milli == 10000, (
            "the speculative UpdateItem consumed these tokens; rollback skipped compensation because the lease was born _committed=True"
        )
