"""AUTO-GENERATED by scripts/generate_sync.py - DO NOT EDIT.

Source: test_config_cache.py

This module provides synchronous versions of the async classes.
Changes should be made to the source file, then regenerated.
"""

import threading
import time
from unittest.mock import MagicMock, Mock

from zae_limiter.models import Limit
from zae_limiter.sync_config_cache import _NO_CONFIG, CacheStats, SyncConfigCache


class TestCacheStats:
    """Tests for CacheStats dataclass."""

    def test_cache_stats_defaults(self) -> None:
        """Test CacheStats default values."""
        stats = CacheStats()
        assert stats.hits == 0
        assert stats.misses == 0
        assert stats.size == 0
        assert stats.ttl_seconds == 0

    def test_cache_stats_as_dict(self) -> None:
        """Test CacheStats.as_dict() returns expected format."""
        stats = CacheStats(hits=100, misses=10, size=5, ttl_seconds=60)
        result = stats.as_dict()
        assert result == {"hits": 100, "misses": 10, "size": 5, "ttl": 60}


class TestConfigCacheBasics:
    """Tests for SyncConfigCache basic functionality."""

    def test_cache_enabled_by_default(self) -> None:
        """Test cache is enabled with default TTL."""
        cache = SyncConfigCache()
        assert cache.enabled is True
        assert cache.ttl_seconds == 60

    def test_cache_disabled_when_ttl_zero(self) -> None:
        """Test TTL=0 disables caching."""
        cache = SyncConfigCache(ttl_seconds=0)
        assert cache.enabled is False

    def test_get_stats_empty_cache(self) -> None:
        """Test get_stats on empty cache."""
        cache = SyncConfigCache(ttl_seconds=60)
        stats = cache.get_stats()
        assert stats.hits == 0
        assert stats.misses == 0
        assert stats.size == 0
        assert stats.ttl_seconds == 60


class TestConfigCacheSystemDefaults:
    """Tests for system defaults caching."""

    def test_system_defaults_cache_miss(self) -> None:
        """Test cache miss for system defaults."""
        cache = SyncConfigCache(ttl_seconds=60)
        limits = [Limit.per_minute("tpm", 10000)]
        fetch_fn = MagicMock(return_value=(limits, "allow"))
        result = cache.get_system_defaults(fetch_fn)
        assert result == (limits, "allow")
        fetch_fn.assert_called_once()
        stats = cache.get_stats()
        assert stats.misses == 1
        assert stats.hits == 0

    def test_system_defaults_cache_hit(self) -> None:
        """Test cache hit for system defaults."""
        cache = SyncConfigCache(ttl_seconds=60)
        limits = [Limit.per_minute("tpm", 10000)]
        fetch_fn = MagicMock(return_value=(limits, "allow"))
        cache.get_system_defaults(fetch_fn)
        result = cache.get_system_defaults(fetch_fn)
        assert result == (limits, "allow")
        fetch_fn.assert_called_once()
        stats = cache.get_stats()
        assert stats.misses == 1
        assert stats.hits == 1

    def test_system_defaults_cache_expired(self) -> None:
        """Test cache expiration for system defaults."""
        cache = SyncConfigCache(ttl_seconds=1)
        limits1 = [Limit.per_minute("tpm", 10000)]
        limits2 = [Limit.per_minute("tpm", 20000)]
        fetch_fn = MagicMock(side_effect=[(limits1, "allow"), (limits2, "block")])
        result1 = cache.get_system_defaults(fetch_fn)
        assert result1 == (limits1, "allow")
        time.sleep(1.1)
        result2 = cache.get_system_defaults(fetch_fn)
        assert result2 == (limits2, "block")
        assert fetch_fn.call_count == 2

    def test_system_defaults_disabled_cache(self) -> None:
        """Test system defaults with disabled cache (TTL=0)."""
        cache = SyncConfigCache(ttl_seconds=0)
        limits = [Limit.per_minute("tpm", 10000)]
        fetch_fn = MagicMock(return_value=(limits, "allow"))
        cache.get_system_defaults(fetch_fn)
        cache.get_system_defaults(fetch_fn)
        assert fetch_fn.call_count == 2

    def test_system_defaults_sync_cache_hit(self) -> None:
        """Test sync cache hit for system defaults."""
        cache = SyncConfigCache(ttl_seconds=60)
        limits = [Limit.per_minute("tpm", 10000)]
        fetch_fn = Mock(return_value=(limits, "allow"))
        cache.get_system_defaults(fetch_fn)
        result = cache.get_system_defaults(fetch_fn)
        assert result == (limits, "allow")
        fetch_fn.assert_called_once()


class TestConfigCacheResourceDefaults:
    """Tests for resource defaults caching."""

    def test_resource_defaults_cache_miss(self) -> None:
        """Test cache miss for resource defaults."""
        cache = SyncConfigCache(ttl_seconds=60)
        limits = [Limit.per_minute("tpm", 10000)]
        fetch_fn = MagicMock(return_value=limits)
        result = cache.get_resource_defaults("gpt-4", fetch_fn)
        assert result == limits
        fetch_fn.assert_called_once_with("gpt-4")

    def test_resource_defaults_cache_hit(self) -> None:
        """Test cache hit for resource defaults."""
        cache = SyncConfigCache(ttl_seconds=60)
        limits = [Limit.per_minute("tpm", 10000)]
        fetch_fn = MagicMock(return_value=limits)
        cache.get_resource_defaults("gpt-4", fetch_fn)
        result = cache.get_resource_defaults("gpt-4", fetch_fn)
        assert result == limits
        fetch_fn.assert_called_once()

    def test_resource_defaults_different_resources(self) -> None:
        """Test separate cache entries for different resources."""
        cache = SyncConfigCache(ttl_seconds=60)
        limits_gpt4 = [Limit.per_minute("tpm", 10000)]
        limits_gpt35 = [Limit.per_minute("tpm", 5000)]

        def fetch_fn(resource: str) -> list[Limit]:
            if resource == "gpt-4":
                return limits_gpt4
            return limits_gpt35

        fetch_mock = MagicMock(side_effect=fetch_fn)
        result1 = cache.get_resource_defaults("gpt-4", fetch_mock)
        result2 = cache.get_resource_defaults("gpt-3.5", fetch_mock)
        result3 = cache.get_resource_defaults("gpt-4", fetch_mock)
        assert result1 == limits_gpt4
        assert result2 == limits_gpt35
        assert result3 == limits_gpt4
        assert fetch_mock.call_count == 2

    def test_resource_defaults_sync_cache_hit(self) -> None:
        """Test sync cache hit for resource defaults."""
        cache = SyncConfigCache(ttl_seconds=60)
        limits = [Limit.per_minute("tpm", 10000)]
        fetch_fn = Mock(return_value=limits)
        cache.get_resource_defaults("gpt-4", fetch_fn)
        result = cache.get_resource_defaults("gpt-4", fetch_fn)
        assert result == limits
        fetch_fn.assert_called_once()


class TestConfigCacheEntityLimits:
    """Tests for entity limits caching with negative caching."""

    def test_entity_limits_cache_miss(self) -> None:
        """Test cache miss for entity limits."""
        cache = SyncConfigCache(ttl_seconds=60)
        limits = [Limit.per_minute("tpm", 10000)]
        fetch_fn = MagicMock(return_value=limits)
        result = cache.get_entity_limits("user-1", "gpt-4", fetch_fn)
        assert result == limits
        fetch_fn.assert_called_once_with("user-1", "gpt-4")

    def test_entity_limits_cache_hit(self) -> None:
        """Test cache hit for entity limits."""
        cache = SyncConfigCache(ttl_seconds=60)
        limits = [Limit.per_minute("tpm", 10000)]
        fetch_fn = MagicMock(return_value=limits)
        cache.get_entity_limits("user-1", "gpt-4", fetch_fn)
        result = cache.get_entity_limits("user-1", "gpt-4", fetch_fn)
        assert result == limits
        fetch_fn.assert_called_once()

    def test_entity_limits_negative_caching(self) -> None:
        """Test negative caching for entities without config."""
        cache = SyncConfigCache(ttl_seconds=60)
        fetch_fn = MagicMock(return_value=[])
        result1 = cache.get_entity_limits("user-1", "gpt-4", fetch_fn)
        assert result1 == []
        result2 = cache.get_entity_limits("user-1", "gpt-4", fetch_fn)
        assert result2 == []
        fetch_fn.assert_called_once()

    def test_entity_limits_different_entities(self) -> None:
        """Test separate cache entries for different entity×resource pairs."""
        cache = SyncConfigCache(ttl_seconds=60)
        limits = [Limit.per_minute("tpm", 10000)]
        fetch_fn = MagicMock(return_value=limits)
        cache.get_entity_limits("user-1", "gpt-4", fetch_fn)
        cache.get_entity_limits("user-1", "gpt-3.5", fetch_fn)
        cache.get_entity_limits("user-2", "gpt-4", fetch_fn)
        assert fetch_fn.call_count == 3

    def test_entity_limits_sync_cache_hit(self) -> None:
        """Test sync cache hit for entity limits."""
        cache = SyncConfigCache(ttl_seconds=60)
        limits = [Limit.per_minute("tpm", 10000)]
        fetch_fn = Mock(return_value=limits)
        cache.get_entity_limits("user-1", "gpt-4", fetch_fn)
        result = cache.get_entity_limits("user-1", "gpt-4", fetch_fn)
        assert result == limits
        fetch_fn.assert_called_once()

    def test_entity_limits_sync_negative_caching(self) -> None:
        """Test negative caching in sync mode."""
        cache = SyncConfigCache(ttl_seconds=60)
        fetch_fn = Mock(return_value=[])
        result1 = cache.get_entity_limits("user-1", "gpt-4", fetch_fn)
        result2 = cache.get_entity_limits("user-1", "gpt-4", fetch_fn)
        assert result1 == []
        assert result2 == []
        fetch_fn.assert_called_once()


class TestConfigCacheInvalidation:
    """Tests for cache invalidation."""

    def test_invalidate_clears_all_entries(self) -> None:
        """Test that invalidate() clears all cache entries."""
        cache = SyncConfigCache(ttl_seconds=60)
        system_fetch = MagicMock(return_value=([Limit.per_minute("tpm", 10000)], "allow"))
        resource_fetch = MagicMock(return_value=[Limit.per_minute("tpm", 5000)])
        entity_fetch = MagicMock(return_value=[Limit.per_minute("tpm", 1000)])
        cache.get_system_defaults(system_fetch)
        cache.get_resource_defaults("gpt-4", resource_fetch)
        cache.get_entity_limits("user-1", "gpt-4", entity_fetch)
        stats = cache.get_stats()
        assert stats.size == 3
        cache.invalidate()
        stats = cache.get_stats()
        assert stats.size == 0
        cache.get_system_defaults(system_fetch)
        cache.get_resource_defaults("gpt-4", resource_fetch)
        cache.get_entity_limits("user-1", "gpt-4", entity_fetch)
        assert system_fetch.call_count == 2
        assert resource_fetch.call_count == 2
        assert entity_fetch.call_count == 2

    def test_invalidate_async_clears_all_entries(self) -> None:
        """Test that invalidate_async() clears all cache entries."""
        cache = SyncConfigCache(ttl_seconds=60)
        system_fetch = MagicMock(return_value=([Limit.per_minute("tpm", 10000)], "allow"))
        cache.get_system_defaults(system_fetch)
        stats = cache.get_stats()
        assert stats.size == 1
        cache.invalidate_async()
        stats = cache.get_stats()
        assert stats.size == 0


class TestConfigCacheStats:
    """Tests for cache statistics."""

    def test_stats_track_hits_and_misses(self) -> None:
        """Test that stats accurately track hits and misses."""
        cache = SyncConfigCache(ttl_seconds=60)
        fetch_fn = MagicMock(return_value=([Limit.per_minute("tpm", 10000)], "allow"))
        cache.get_system_defaults(fetch_fn)
        cache.invalidate()
        cache.get_system_defaults(fetch_fn)
        cache.invalidate()
        cache.get_system_defaults(fetch_fn)
        for _ in range(5):
            cache.get_system_defaults(fetch_fn)
        stats = cache.get_stats()
        assert stats.misses == 3
        assert stats.hits == 5

    def test_stats_track_size(self) -> None:
        """Test that stats accurately track cache size."""
        cache = SyncConfigCache(ttl_seconds=60)
        system_fetch = MagicMock(return_value=([Limit.per_minute("tpm", 10000)], "allow"))
        resource_fetch = MagicMock(return_value=[Limit.per_minute("tpm", 5000)])
        entity_fetch = MagicMock(return_value=[Limit.per_minute("tpm", 1000)])
        cache.get_system_defaults(system_fetch)
        assert cache.get_stats().size == 1
        cache.get_resource_defaults("gpt-4", resource_fetch)
        assert cache.get_stats().size == 2
        cache.get_entity_limits("user-1", "gpt-4", entity_fetch)
        assert cache.get_stats().size == 3


class TestConfigCacheThreadSafety:
    """Tests for thread safety."""

    def test_sync_operations_are_thread_safe(self) -> None:
        """Test that sync operations are thread-safe."""
        cache = SyncConfigCache(ttl_seconds=60)
        call_count = 0
        lock = threading.Lock()

        def fetch_fn() -> tuple[list[Limit], str | None]:
            nonlocal call_count
            with lock:
                call_count += 1
            time.sleep(0.01)
            return ([Limit.per_minute("tpm", 10000)], "allow")

        results: list[tuple[list[Limit], str | None]] = []

        def worker() -> None:
            for _ in range(10):
                result = cache.get_system_defaults(fetch_fn)
                with lock:
                    results.append(result)

        threads = [threading.Thread(target=worker) for _ in range(5)]
        for t in threads:
            t.start()
        for t in threads:
            t.join()
        assert len(results) == 50
        expected = ([Limit.per_minute("tpm", 10000)], "allow")
        for result in results:
            assert result == expected
        assert call_count >= 1
        assert call_count < 10


class TestConfigCacheAsyncSafety:
    """Tests for async safety."""


class TestConfigCacheDisabledBranches:
    """Tests for cache disabled branches (TTL=0) to ensure 100% coverage."""

    def test_system_defaults_sync_disabled_cache(self) -> None:
        """Test sync system defaults with disabled cache (TTL=0)."""
        cache = SyncConfigCache(ttl_seconds=0)
        limits = [Limit.per_minute("tpm", 10000)]
        fetch_fn = Mock(return_value=(limits, "allow"))
        cache.get_system_defaults(fetch_fn)
        cache.get_system_defaults(fetch_fn)
        assert fetch_fn.call_count == 2

    def test_resource_defaults_disabled_cache(self) -> None:
        """Test async resource defaults with disabled cache (TTL=0)."""
        cache = SyncConfigCache(ttl_seconds=0)
        limits = [Limit.per_minute("rpm", 1000)]
        fetch_fn = MagicMock(return_value=limits)
        cache.get_resource_defaults("gpt-4", fetch_fn)
        cache.get_resource_defaults("gpt-4", fetch_fn)
        assert fetch_fn.call_count == 2

    def test_resource_defaults_sync_disabled_cache(self) -> None:
        """Test sync resource defaults with disabled cache (TTL=0)."""
        cache = SyncConfigCache(ttl_seconds=0)
        limits = [Limit.per_minute("rpm", 1000)]
        fetch_fn = Mock(return_value=limits)
        cache.get_resource_defaults("gpt-4", fetch_fn)
        cache.get_resource_defaults("gpt-4", fetch_fn)
        assert fetch_fn.call_count == 2

    def test_entity_limits_disabled_cache(self) -> None:
        """Test async entity limits with disabled cache (TTL=0)."""
        cache = SyncConfigCache(ttl_seconds=0)
        limits = [Limit.per_minute("rpm", 500)]
        fetch_fn = MagicMock(return_value=limits)
        cache.get_entity_limits("user-1", "gpt-4", fetch_fn)
        cache.get_entity_limits("user-1", "gpt-4", fetch_fn)
        assert fetch_fn.call_count == 2

    def test_entity_limits_sync_disabled_cache(self) -> None:
        """Test sync entity limits with disabled cache (TTL=0)."""
        cache = SyncConfigCache(ttl_seconds=0)
        limits = [Limit.per_minute("rpm", 500)]
        fetch_fn = Mock(return_value=limits)
        cache.get_entity_limits("user-1", "gpt-4", fetch_fn)
        cache.get_entity_limits("user-1", "gpt-4", fetch_fn)
        assert fetch_fn.call_count == 2


class TestConfigCacheNegativeCachingSentinel:
    """Tests for negative caching sentinel value."""

    def test_no_config_sentinel_is_unique(self) -> None:
        """Test that _NO_CONFIG sentinel is a unique object."""
        assert _NO_CONFIG is not None
        assert _NO_CONFIG != []
        assert _NO_CONFIG != []
